# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from auth import Ui_SignInWindow
from registration import Ui_SignUpWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(591, 356)
        MainWindow.setMinimumSize(QtCore.QSize(591, 356))
        MainWindow.setMaximumSize(QtCore.QSize(591, 356))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 50, 393, 39))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 120, 380, 40))
        self.label_2.setMaximumSize(QtCore.QSize(380, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(110, 210, 381, 46))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.buttonSignIn = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.buttonSignIn.setFont(font)
        self.buttonSignIn.setAutoFillBackground(True)
        self.buttonSignIn.setObjectName("buttonSignIn")
        self.buttonSignUp = QtWidgets.QPushButton(self.splitter)
        self.buttonSignIn.clicked.connect(self.openSignInWindow)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.buttonSignUp.setFont(font)
        self.buttonSignUp.setAutoFillBackground(True)
        self.buttonSignUp.setObjectName("buttonSignUp")
        self.buttonSignUp.clicked.connect(self.openSignUpWindow)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 591, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Обучающее приложение \"Физика. Электричество\""))
        self.label.setText(_translate("MainWindow", "Обучающее приложение"))
        self.label_2.setText(_translate("MainWindow", "\"Физика. Электричество\""))
        self.buttonSignIn.setText(_translate("MainWindow", "Войти"))
        self.buttonSignUp.setText(_translate("MainWindow", "Регистрация"))

    def openSignInWindow(self):
        self.window = QtWidgets.QMainWindow()  # Create a new window instance
        self.ui = Ui_SignInWindow()  # Create an instance of the new window's UI
        self.ui.setupUi(self.window)
        self.window.show()  # Show the new window
        MainWindow.hide()  # Close the current main window

    def openSignUpWindow(self):
        self.window = QtWidgets.QMainWindow()  # Create a new window instance
        self.ui = Ui_SignUpWindow()  # Create an instance of the new window's UI
        self.ui.setupUi(self.window)
        self.window.show()  # Show the new window
        MainWindow.close()  # Close the current main window

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())