# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignInWindow(object):
    def setupUi(self, AuthWindows):
        AuthWindows.setObjectName("AuthWindows")
        AuthWindows.resize(506, 296)
        AuthWindows.setMinimumSize(QtCore.QSize(506, 296))
        AuthWindows.setMaximumSize(QtCore.QSize(506, 296))
        self.centralwidget = QtWidgets.QWidget(AuthWindows)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(170, 100, 231, 22))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 100, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 140, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 140, 231, 22))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 190, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 30, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 0, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        AuthWindows.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AuthWindows)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 506, 26))
        self.menubar.setObjectName("menubar")
        AuthWindows.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AuthWindows)
        self.statusbar.setObjectName("statusbar")
        AuthWindows.setStatusBar(self.statusbar)

        self.retranslateUi(AuthWindows)
        QtCore.QMetaObject.connectSlotsByName(AuthWindows)

    def retranslateUi(self, AuthWindows):
        _translate = QtCore.QCoreApplication.translate
        AuthWindows.setWindowTitle(_translate("AuthWindows", "Авторизация"))
        self.label.setText(_translate("AuthWindows", "Логин:"))
        self.label_2.setText(_translate("AuthWindows", "Пароль:"))
        self.pushButton.setText(_translate("AuthWindows", "Войти"))
        self.label_3.setText(_translate("AuthWindows", "Авторизация"))
        self.pushButton_2.setText(_translate("AuthWindows", "<"))


